### ISSUE TITLE
classes with same name and attribute in category module and feeds, reverse accessor clash

### ISSUE THREAD

**Issue by jeromecc** [andreasofthings/feeds#7]
Hello!

./manage.py check identified an issue:

django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:
```                                                                                                                                             
ERRORS:
category.Tag.content_type: (fields.E304) Reverse accessor for 'Tag.content_type' clashes with reverse accessor for 'Tag.content_type'.
        HINT: Add or change a related_name argument to the definition for 'Tag.content_type' or 'Tag.content_type'.                                                         
feeds.Tag.content_type: (fields.E304) Reverse accessor for 'Tag.content_type' clashes with reverse accessor for 'Tag.content_type'.
        HINT: Add or change a related_name argument to the definition for 'Tag.content_type' or 'Tag.content_type'.
```
Both category module and feeds contain a class called Tag with a  ForeignKey called content_type.

Thanks.
